---
kind: pipeline
name: windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: publish-windows-1809
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: rancher/kubelet-pause
      tag: "${DRONE_TAG}-windows-1809"
      build_args:
        - SERVERCORE_VERSION=1809
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
name: manifest

steps:
  - name: push-manifest
    image: plugins/manifest:1.1.0
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "rancher/kubelet-pause:${DRONE_TAG}"
      template: "rancher/kubelet-pause:${DRONE_TAG}-OS-ARCH"
      platforms:
        - windows/1809
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag
depends_on:
  - windows-1809
