---
kind: pipeline
name: windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: publish-windows-1809
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: rancher/kubelet-pause
      tag: "${DRONE_TAG}-windows-1809"
      build_args:
        - SERVERCORE_VERSION=1809
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
name: windows-1903

platform:
  os: windows
  arch: amd64
  version: 1903

steps:
  - name: publish-windows-1903
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: rancher/kubelet-pause
      tag: "${DRONE_TAG}-windows-1903"
      build_args:
        - SERVERCORE_VERSION=1903
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
name: windows-1909

platform:
  os: windows
  arch: amd64
  version: 1909

steps:
  - name: publish-windows-1909
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: rancher/kubelet-pause
      tag: "${DRONE_TAG}-windows-1909"
      build_args:
        - SERVERCORE_VERSION=1909
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
name: manifest

steps:
  - name: push-manifest
    image: ibuildthecloud/manifest:v1.2.3-patch1
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      spec: manifest.tmpl
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag
depends_on:
  - windows-1809
  - windows-1903
  - windows-1909